Update buy-ravencoin.md, to include foundational donations
RavenProject/ravenproject.github.io pull request #183
Opened 2021-03-28 14:17 UTC by ladams1776

We want to let the users know that exchange fees are partly
donated back to the raven coin foundation

2021-03-28 14:18 UTC, ladams1776 commented on _pages/buy-ravencoin.md
> +                  <span><i class="zmdi zmdi-balance"></i> &nbsp; Donates to foundation</span>
perhaps the `&nbsp;` is overkill. I just wanted to ensure padding. not use to jekyll.

2021-03-29 21:45 UTC, ladams1776 commented
To address Issue: https://github.com/RavenProject/ravenproject.github.io/issues/67

2021-03-29 22:02 UTC, ladams1776 commented on _data/exchanges.yml
> +  donates_to_project: false
Do we want to add Dynx? I see the issue states Dynx as one of the exchanges that donates back to the foundation

2021-03-29 22:04 UTC, ladams1776 commented
Test Evidence:
![Screen Shot 2021-03-29 at 6 03 15 PM](https://user-images.githubusercontent.com/13687739/112905837-22ac5180-90b9-11eb-91a1-f3bd3c3e05b6.png)

![Screen Shot 2021-03-29 at 6 03 27 PM](https://user-images.githubusercontent.com/13687739/112905842-25a74200-90b9-11eb-80b5-fb254013557a.png)

2021-04-01 10:32 UTC, jeroz1 commented on _data/exchanges.yml
> +  donates_to_project: false
Dynx is gone

2021-04-01 10:37 UTC, jeroz1 commented
I like the changes a lot! 

Would it be possible to fix the Exchange title alignment? Currently, the badge pushes the name down. 

Come to think of it. Can we get rid of the exchange titles? This information is already in the logos themselves. Extra titles at the bottom of the logos seem pretty redundant to me. Let's do that in a separate PR.

2021-04-11 03:20 UTC, ladams1776 commented
> I like the changes a lot!
> 
> Would it be possible to fix the Exchange title alignment? Currently, the badge pushes the name down.
> 
> Come to think of it. Can we get rid of the exchange titles? This information is already in the logos themselves. Extra titles at the bottom of the logos seem pretty redundant to me. Let's do that in a separate PR.

I think this is what we are looking for.
<img width="623" alt="Screen Shot 2021-04-03 at 10 19 02 PM" src="https://user-images.githubusercontent.com/13687739/114291184-5a20e380-9a53-11eb-9356-6ab3458bc0df.png">

2021-04-13 18:07 UTC, jeroz1 requested changes
_data/exchanges.yml needs a new line at the end of the file

2021-04-13 23:12 UTC, ladams1776 commented
> _data/exchanges.yml needs a new line at the end of the file

ok, I think that should do it. Just updated it.

2021-04-14 05:27 UTC, jeroz1 approved these changes

2021-04-14 05:27 UTC, merged