Add Cruxpool to the list of mining pools
RavenProject/ravenproject.github.io pull request #207
Opened 2021-07-06 11:46 UTC by LucasNoga

Hey there, 

could you please add **https://cruxpool.com/** to the list of mining pools.

Thanks in advance

2021-07-08 07:14 UTC, jeroz1 requested changes
Looks like it needs an extra new line at the end.

2021-07-09 13:46 UTC, LucasNoga commented
Thanks @jeroz1 I will change that

2021-07-09 14:02 UTC, LucasNoga commented
As requested I added an extra new line in the file _data/pools.

Lucas

2021-07-09 14:08 UTC, jeroz1 approved these changes

2021-07-09 14:08 UTC, merged