Wallet Links
RavenProject/ravenproject.github.io pull request #275
Opened 2024-04-30 21:50 UTC by lastmeta

Currently the wallet link for Android is dead. I added the link for Moontree's Android wallet in it's place. I also replaced the ios wallet link with the Moontree's Wallet link for ios.

2024-05-03 19:54 UTC, Tylerlhess commented
I am split on this. I like the idea of having the link fixed. I don't like that this is basically endorsing Moontree wallet as the community accepted default. I would feel better If all of the asset supported apps would be listed with the download link linking to a generic search for RVN wallets. That being said I also see value in having the different app links there but having it more like a table. Having the app logo in column 1, Ios link in column2, and Android link to it in column 3. But making sure to do that for every asset aware wallet.

Also I think it would be great to have this page / these links checked on a regular basis. Checking for things such as that the links work and that the apps/wallets listed here are regularly update. (Oh! We could list the apps in order of latest release date newest first. Software maintenance is a much better listing order than alphabetical). Would checking on releasees and proper ordering and linkage  be something you would want to take on? I have no power or sway either way just trying to lead the herd of cats in a coherent direction.

2024-07-22 16:58 UTC, jeroz1 requested changes
The android link seems to be broken

2025-09-01 00:31 UTC, lastmeta reviewed
I was unaware that the that original Moontree app was still live

2025-09-01 15:11 UTC, jeroz1 commented
I think the best option would be removing the mobile wallet links and add a "3rd Party Asset Aware Wallets" section. This should be above the 3rd party wallets since they fully support Ravencoin.

Magic Wallet should be in that section.

2025-09-01 15:11 UTC, closed without merging

2025-09-01 16:50 UTC, hans-schmidt commented
That makes sense. But be aware that Magic wallet is also intermittently offline. Future support is undecided, and it needs some updates to fix frequent server crashes.